services:
  auth-server:
    build:
      context: ./auth-server
      dockerfile: .dockerfile
    container_name: auth-server
    ports:
      - '4000:3000'
    env_file:
      - path: .env
        required: true

  back-end:
    build:
      context: ./back-end
      dockerfile: .dockerfile
    container_name: back-end
    ports:
      - '5000:3000'
    env_file:
      - path: .env
        required: true

  front-end:
    build:
      context: ./front-end
      dockerfile: .dockerfile
    container_name: front-end
    ports:
      - '3000:3000'

  db:
    image: mongo
    container_name: MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  nginx-front-end:
    image: nginx:alpine
    volumes:
      - ./nginx/front-end.conf:/etc/nginx/nginx.conf
      - ./comp3000-el-comercio.xyz-ssl-bundle:/etc/nginx/ssl:ro  # Attatch PorkBun SLL Bundle
    ports:
      - "443:443"  # Expose HTTPS to the outside world
    depends_on:
      - front-end