services:
  auth-server:
    build:
      context: ./auth-server
      dockerfile: .dockerfile
    ports:
      - '4000:3000'

  back-end:
    build:
      context: ./back-end
      dockerfile: .dockerfile
    ports:
      - '5000:3000'

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017